/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitIdeaRouteImport } from './routes/submit-idea'
import { Route as QaManagerRouteImport } from './routes/qa-manager'
import { Route as QaCoordinatorRouteImport } from './routes/qa-coordinator'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IdeasRouteImport } from './routes/ideas'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IdeasIndexRouteImport } from './routes/ideas.index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ManageUsersRouteImport } from './routes/manage/users'
import { Route as ManageDepartmentsRouteImport } from './routes/manage/departments'
import { Route as ManageCategoriesRouteImport } from './routes/manage/categories'
import { Route as IdeasIdeaIdRouteImport } from './routes/ideas.$ideaId'

const SubmitIdeaRoute = SubmitIdeaRouteImport.update({
  id: '/submit-idea',
  path: '/submit-idea',
  getParentRoute: () => rootRouteImport,
} as any)
const QaManagerRoute = QaManagerRouteImport.update({
  id: '/qa-manager',
  path: '/qa-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const QaCoordinatorRoute = QaCoordinatorRouteImport.update({
  id: '/qa-coordinator',
  path: '/qa-coordinator',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasRoute = IdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIndexRoute = IdeasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IdeasRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageUsersRoute = ManageUsersRouteImport.update({
  id: '/manage/users',
  path: '/manage/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageDepartmentsRoute = ManageDepartmentsRouteImport.update({
  id: '/manage/departments',
  path: '/manage/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageCategoriesRoute = ManageCategoriesRouteImport.update({
  id: '/manage/categories',
  path: '/manage/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const IdeasIdeaIdRoute = IdeasIdeaIdRouteImport.update({
  id: '/$ideaId',
  path: '/$ideaId',
  getParentRoute: () => IdeasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/qa-coordinator': typeof QaCoordinatorRoute
  '/qa-manager': typeof QaManagerRoute
  '/submit-idea': typeof SubmitIdeaRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/departments': typeof ManageDepartmentsRoute
  '/manage/users': typeof ManageUsersRoute
  '/admin': typeof AdminIndexRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/qa-coordinator': typeof QaCoordinatorRoute
  '/qa-manager': typeof QaManagerRoute
  '/submit-idea': typeof SubmitIdeaRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/departments': typeof ManageDepartmentsRoute
  '/manage/users': typeof ManageUsersRoute
  '/admin': typeof AdminIndexRoute
  '/ideas': typeof IdeasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ideas': typeof IdeasRouteWithChildren
  '/login': typeof LoginRoute
  '/qa-coordinator': typeof QaCoordinatorRoute
  '/qa-manager': typeof QaManagerRoute
  '/submit-idea': typeof SubmitIdeaRoute
  '/ideas/$ideaId': typeof IdeasIdeaIdRoute
  '/manage/categories': typeof ManageCategoriesRoute
  '/manage/departments': typeof ManageDepartmentsRoute
  '/manage/users': typeof ManageUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/ideas/': typeof IdeasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ideas'
    | '/login'
    | '/qa-coordinator'
    | '/qa-manager'
    | '/submit-idea'
    | '/ideas/$ideaId'
    | '/manage/categories'
    | '/manage/departments'
    | '/manage/users'
    | '/admin'
    | '/ideas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/qa-coordinator'
    | '/qa-manager'
    | '/submit-idea'
    | '/ideas/$ideaId'
    | '/manage/categories'
    | '/manage/departments'
    | '/manage/users'
    | '/admin'
    | '/ideas'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/ideas'
    | '/login'
    | '/qa-coordinator'
    | '/qa-manager'
    | '/submit-idea'
    | '/ideas/$ideaId'
    | '/manage/categories'
    | '/manage/departments'
    | '/manage/users'
    | '/admin/'
    | '/ideas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  IdeasRoute: typeof IdeasRouteWithChildren
  LoginRoute: typeof LoginRoute
  QaCoordinatorRoute: typeof QaCoordinatorRoute
  QaManagerRoute: typeof QaManagerRoute
  SubmitIdeaRoute: typeof SubmitIdeaRoute
  ManageCategoriesRoute: typeof ManageCategoriesRoute
  ManageDepartmentsRoute: typeof ManageDepartmentsRoute
  ManageUsersRoute: typeof ManageUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-idea': {
      id: '/submit-idea'
      path: '/submit-idea'
      fullPath: '/submit-idea'
      preLoaderRoute: typeof SubmitIdeaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-manager': {
      id: '/qa-manager'
      path: '/qa-manager'
      fullPath: '/qa-manager'
      preLoaderRoute: typeof QaManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-coordinator': {
      id: '/qa-coordinator'
      path: '/qa-coordinator'
      fullPath: '/qa-coordinator'
      preLoaderRoute: typeof QaCoordinatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas': {
      id: '/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof IdeasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/': {
      id: '/ideas/'
      path: '/'
      fullPath: '/ideas/'
      preLoaderRoute: typeof IdeasIndexRouteImport
      parentRoute: typeof IdeasRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/users': {
      id: '/manage/users'
      path: '/manage/users'
      fullPath: '/manage/users'
      preLoaderRoute: typeof ManageUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/departments': {
      id: '/manage/departments'
      path: '/manage/departments'
      fullPath: '/manage/departments'
      preLoaderRoute: typeof ManageDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage/categories': {
      id: '/manage/categories'
      path: '/manage/categories'
      fullPath: '/manage/categories'
      preLoaderRoute: typeof ManageCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ideas/$ideaId': {
      id: '/ideas/$ideaId'
      path: '/$ideaId'
      fullPath: '/ideas/$ideaId'
      preLoaderRoute: typeof IdeasIdeaIdRouteImport
      parentRoute: typeof IdeasRoute
    }
  }
}

interface IdeasRouteChildren {
  IdeasIdeaIdRoute: typeof IdeasIdeaIdRoute
  IdeasIndexRoute: typeof IdeasIndexRoute
}

const IdeasRouteChildren: IdeasRouteChildren = {
  IdeasIdeaIdRoute: IdeasIdeaIdRoute,
  IdeasIndexRoute: IdeasIndexRoute,
}

const IdeasRouteWithChildren = IdeasRoute._addFileChildren(IdeasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  IdeasRoute: IdeasRouteWithChildren,
  LoginRoute: LoginRoute,
  QaCoordinatorRoute: QaCoordinatorRoute,
  QaManagerRoute: QaManagerRoute,
  SubmitIdeaRoute: SubmitIdeaRoute,
  ManageCategoriesRoute: ManageCategoriesRoute,
  ManageDepartmentsRoute: ManageDepartmentsRoute,
  ManageUsersRoute: ManageUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
